name: Compilar y desplegar

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'LibraryAPI/**'
      - 'LibraryAPITests/**'
      - '.github/workflows/compilar-y-desplegar.yml'
# Environment Variables      
env:
  VERSION_DOTNET: 9
  AZURE_APP_SERVICE_NOMBRE: library-api-vs-code
  AZURE_APP_SERVICE_UBICACION_PAQUETE: '.' # The package will be located in the same location that I'm

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      proyecto: LibraryAPI/LibraryAPI.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: ${{ env.VERSION_DOTNET }}

      - name: Obteniendo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Realizar pruebas
        run: dotnet test --no-build
        
      - name: Publicar el web API # This step create the buil
        run: dotnet publish $proyecto -c Release -o miapp --runtime win-x86

      - name: Cargar Artefacto # This step take the build into an artifac
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./miapp
          name: build # with this name the artifac, to be used for another process
  despliegue:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build # Tipically the jobs could load simultaniuslly but we need build finish first
    steps: 
      - name: Obtener los artefactos
        uses: actions/download-artifact@v4.3.0
        with:
          name: build

      - name: Desplegar al Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NOMBRE }}
          publish-profile: ${{ secrets.AZURE_PERFIL_PUBLICO }}
          package: ${{ env.AZURE_APP_SERVICE_UBICACION_PAQUETE }}
        
        
          
          
      

        
        
        
  
  
